GET http://localhost:3000

###

POST http://localhost:3000
Content-Type: application/json
Accept: application/json

{
   "todo": "PHP"
}

###

PUT http://localhost:3000
Content-Type: application/json
Accept: application/json

{
   "id" : 0,
   "todo" : "Programmer Zaman Now"
}

###

DELETE http://localhost:3000
Content-Type: application/json
Accept: application/json

{
   "id" : 100
}
